---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: hello-world-service
  name: hello-world-service
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: induction-hello-world
